### ISSUE TITLE
Railsy web refresher suggestion

### ISSUE THREAD

**Issue by AgonIdrizi** [TheOdinProject/rails_course#141]
Hi all,
I found a great video for http request/responds (headers)(methods), which i thought would be great to include at the 'Railsy web refresher'(Introduction to rails course).
https://code.tutsplus.com/tutorials/how-the-web-works-http-and-the-web-server--cms-25971
It's just a suggestion, sorry if this is not the place to make suggestion, thought would be better to write here at issues section than in the forum.
Thanks.

**Comment by KevinMulhern** [comment]
Hi @AgonIdrizi, thanks for sharing this. If you found it helpful then I'm sure other students will as well. 

Do you think it would be good addition to the assignment or extra resources?

**Comment by AgonIdrizi** [comment]
Hi @KevinMulhern , this visual representation of http, made me understand more deeply whats going on, especially headers on each request.
As the first link on the assignment is more theory-reading, this one i think will left out any doubt about understanding http headers body, as the students will see it live whats happening.
I think would be good to add it in the assignment section, but the last word is from the staff.
Thank You,

**Comment by KevinMulhern** [comment]
Do you fancy creating a pull request to add that to the lesson? 😄
