### ISSUE TITLE
Second link in the assignment for introduction to frameworks broken

### ISSUE THREAD

**Issue by Javier-Machin** [TheOdinProject/rails_course#59]
The second link in the assignment [here](https://github.com/TheOdinProject/rails_course/blob/master/web_development_101/web_development_frameworks/introduction_to_frameworks.md) is dead.

**Comment by KevinMulhern** [comment]
Thanks for reporting this @Javier-Machin. This will be a good opportunity to find a more up to date resource to replace this with.

**Comment by CouchofTomato** [comment]
@KevinMulhern 

This one is a pretty good overview

https://rubygarage.org/blog/technology-stack-for-web-development

**Comment by heyalvaro** [comment]
This link from mozilla lists the frameworks that were mentioned in the dead link
https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Web_frameworks

Additionally, web.archive.org could be used to retrieve the dead link
